directive set /fir/fir:core/fir:core:conc/MAC:acc#14 RESOURCE_NAME MAC:acc#12:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#12 RESOURCE_NAME MAC:acc#12:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc RESOURCE_NAME MAC:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#16 RESOURCE_NAME MAC:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-1:mul:rg
