directive set /fir/fir:core/core/regs:acc.itm REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/regs:vinit.ndx(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/rptr(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/wptr(4:0)#1.sva REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#6.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#3.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/MAC:mux#8.itm REGISTER_NAME MAC:mux#8.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#3.itm REGISTER_NAME MAC:mux#8.itm
directive set /fir/fir:core/core/MAC:mux.itm REGISTER_NAME MAC:mux.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#2.itm REGISTER_NAME MAC:mux.itm
directive set /fir/fir:core/core/wptr(4:0)#4.sva#1 REGISTER_NAME wptr(4:0)#4.sva#1
directive set /fir/fir:core/core/wptr(4:0)#5.lpi#2.dfm REGISTER_NAME wptr(4:0)#4.sva#1
directive set /fir/fir:core/core/MAC:MAC:or#6.itm REGISTER_NAME wptr(4:0)#4.sva#1
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:MAC:nor#11.itm REGISTER_NAME MAC:MAC:nor#11.itm
directive set /fir/fir:core/core/MAC:MAC:nor#8.itm REGISTER_NAME MAC:MAC:nor#11.itm
directive set /fir/fir:core/core/MAC:mux#10.itm REGISTER_NAME MAC:mux#10.itm
directive set /fir/fir:core/core/MAC:mux#9.itm REGISTER_NAME MAC:mux#10.itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-3:mul.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC-3:mul.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC-3:mul.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#2.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#1.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
