directive set /fir/fir:core/fir:core:conc/else:acc RESOURCE_NAME MAC-6:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:acc#2 RESOURCE_NAME MAC-6:acc#2:rg
directive set /fir/fir:core/fir:core:conc/regs:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:acc#1 RESOURCE_NAME MAC-7:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#4 RESOURCE_NAME MAC-7:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#7 RESOURCE_NAME MAC:mux#13:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#13 RESOURCE_NAME MAC:mux#13:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-5:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-5:mul:rg
