directive set /fir/fir:core/core/MAC:acc#30.itm.1 REGISTER_NAME MAC:acc#30.itm.1
directive set /fir/fir:core/core/MAC:acc.itm REGISTER_NAME MAC:acc#30.itm.1
directive set /fir/fir:core/core/MAC:acc#30.itm REGISTER_NAME MAC:acc#30.itm.1
directive set /fir/fir:core/core/MAC:acc#29.itm.1 REGISTER_NAME MAC:acc#29.itm.1
directive set /fir/fir:core/core/MAC:acc#31.itm REGISTER_NAME MAC:acc#29.itm.1
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC:acc#29.itm.1
directive set /fir/fir:core/core/MAC:acc#13.itm.1 REGISTER_NAME MAC:acc#13.itm.1
directive set /fir/fir:core/core/MAC:acc#17.itm REGISTER_NAME MAC:acc#13.itm.1
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC:acc#13.itm.1
directive set /fir/fir:core/core/MAC:acc#12.itm.1 REGISTER_NAME MAC:acc#12.itm.1
directive set /fir/fir:core/core/MAC:acc#16.itm REGISTER_NAME MAC:acc#12.itm.1
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC:acc#12.itm.1
directive set /fir/fir:core/core/MAC:acc#11.itm.1 REGISTER_NAME MAC:acc#11.itm.1
directive set /fir/fir:core/core/MAC:acc#15.itm REGISTER_NAME MAC:acc#11.itm.1
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC:acc#11.itm.1
directive set /fir/fir:core/core/MAC:acc#10.itm.1 REGISTER_NAME MAC:acc#10.itm.1
directive set /fir/fir:core/core/MAC:acc#14.itm REGISTER_NAME MAC:acc#10.itm.1
directive set /fir/fir:core/core/MAC:acc#18.itm REGISTER_NAME MAC:acc#10.itm.1
directive set /fir/fir:core/core/MAC:asn#73.itm REGISTER_NAME MAC:asn#73.itm
directive set /fir/fir:core/core/regs(1).sva REGISTER_NAME MAC:asn#73.itm
directive set /fir/fir:core/core/MAC:asn#90.itm REGISTER_NAME MAC:asn#90.itm
directive set /fir/fir:core/core/asn.ncse.sva REGISTER_NAME MAC:asn#90.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC:acc#6.itm
directive set /fir/fir:core/core/MAC:acc#6.itm.1 REGISTER_NAME MAC:acc#6.itm
directive set /fir/fir:core/core/MAC:acc#9.itm REGISTER_NAME MAC:acc#9.itm
directive set /fir/fir:core/core/MAC:acc#9.itm.1 REGISTER_NAME MAC:acc#9.itm
directive set /fir/fir:core/core/MAC:acc#13.itm REGISTER_NAME MAC:acc#13.itm
directive set /fir/fir:core/core/MAC:acc#7.itm.1 REGISTER_NAME MAC:acc#13.itm
