directive set /fir/fir:core/core/MAC-15:MAC:mux.itm REGISTER_NAME MAC-15:MAC:mux.itm
directive set /fir/fir:core/core/regs(13).sva REGISTER_NAME MAC-15:MAC:mux.itm
directive set /fir/fir:core/core/MAC-16:MAC:mux.itm REGISTER_NAME MAC-16:MAC:mux.itm
directive set /fir/fir:core/core/regs(14).sva REGISTER_NAME MAC-16:MAC:mux.itm
directive set /fir/fir:core/core/MAC-2:MAC:mux.itm REGISTER_NAME MAC-2:MAC:mux.itm
directive set /fir/fir:core/core/regs(0).sva REGISTER_NAME MAC-2:MAC:mux.itm
directive set /fir/fir:core/core/MAC-3:MAC:mux.itm REGISTER_NAME MAC-3:MAC:mux.itm
directive set /fir/fir:core/core/regs(1).sva REGISTER_NAME MAC-3:MAC:mux.itm
directive set /fir/fir:core/core/MAC-4:MAC:mux.itm REGISTER_NAME MAC-4:MAC:mux.itm
directive set /fir/fir:core/core/regs(2).sva REGISTER_NAME MAC-4:MAC:mux.itm
directive set /fir/fir:core/core/MAC-5:MAC:mux.itm REGISTER_NAME MAC-5:MAC:mux.itm
directive set /fir/fir:core/core/regs(3).sva REGISTER_NAME MAC-5:MAC:mux.itm
directive set /fir/fir:core/core/MAC-6:MAC:mux.itm REGISTER_NAME MAC-6:MAC:mux.itm
directive set /fir/fir:core/core/regs(4).sva REGISTER_NAME MAC-6:MAC:mux.itm
directive set /fir/fir:core/core/MAC-7:MAC:mux.itm REGISTER_NAME MAC-7:MAC:mux.itm
directive set /fir/fir:core/core/regs(5).sva REGISTER_NAME MAC-7:MAC:mux.itm
directive set /fir/fir:core/core/MAC-8:MAC:mux.itm REGISTER_NAME MAC-8:MAC:mux.itm
directive set /fir/fir:core/core/regs(6).sva REGISTER_NAME MAC-8:MAC:mux.itm
directive set /fir/fir:core/core/MAC-9:MAC:mux.itm REGISTER_NAME MAC-9:MAC:mux.itm
directive set /fir/fir:core/core/regs(7).sva REGISTER_NAME MAC-9:MAC:mux.itm
directive set /fir/fir:core/core/MAC-10:MAC:mux.itm REGISTER_NAME MAC-10:MAC:mux.itm
directive set /fir/fir:core/core/regs(8).sva REGISTER_NAME MAC-10:MAC:mux.itm
directive set /fir/fir:core/core/MAC-11:MAC:mux.itm REGISTER_NAME MAC-11:MAC:mux.itm
directive set /fir/fir:core/core/regs(9).sva REGISTER_NAME MAC-11:MAC:mux.itm
directive set /fir/fir:core/core/MAC-12:MAC:mux.itm REGISTER_NAME MAC-12:MAC:mux.itm
directive set /fir/fir:core/core/regs(10).sva REGISTER_NAME MAC-12:MAC:mux.itm
directive set /fir/fir:core/core/MAC-13:MAC:mux.itm REGISTER_NAME MAC-13:MAC:mux.itm
directive set /fir/fir:core/core/regs(11).sva REGISTER_NAME MAC-13:MAC:mux.itm
directive set /fir/fir:core/core/MAC-14:MAC:mux.itm REGISTER_NAME MAC-14:MAC:mux.itm
directive set /fir/fir:core/core/regs(12).sva REGISTER_NAME MAC-14:MAC:mux.itm
directive set /fir/fir:core/core/MAC-11:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-13:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-15:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#16.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#11.itm REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC:acc#13.itm REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC:acc#7.itm REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC-10:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-12:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-14:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-16:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-6:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC:acc#15.itm REGISTER_NAME MAC:acc#15.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC:acc#15.itm
