directive set /fir/fir:core/fir:core:conc/MAC-9:acc#1 RESOURCE_NAME MAC-9:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#10 RESOURCE_NAME MAC-9:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#7 RESOURCE_NAME MAC-9:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#3 RESOURCE_NAME MAC-5:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:acc#2 RESOURCE_NAME MAC-5:acc#2:rg
directive set /fir/fir:core/fir:core:conc/regs:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:else:acc RESOURCE_NAME MAC-3:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:else:acc RESOURCE_NAME MAC-3:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#9 RESOURCE_NAME MAC:mux#17:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#17 RESOURCE_NAME MAC:mux#17:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-6:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-6:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
