directive set /fir/fir:core/fir:core:conc/else:acc RESOURCE_NAME MAC:slc(MAC-8:MAC:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC:slc(MAC-8:MAC:acc RESOURCE_NAME MAC:slc(MAC-8:MAC:acc:rg
directive set /fir/fir:core/fir:core:conc/regs:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:else:acc RESOURCE_NAME MAC-3:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:else:acc RESOURCE_NAME MAC-3:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#8 RESOURCE_NAME MAC-2:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#7 RESOURCE_NAME MAC-2:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:acc#1 RESOURCE_NAME MAC-2:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#11 RESOURCE_NAME MAC:mux#11:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#13 RESOURCE_NAME MAC:mux#11:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#18 RESOURCE_NAME MAC:mux#12:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#12 RESOURCE_NAME MAC:mux#12:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-3:mul:rg
