directive set /fir/fir:core/core/regs:acc.itm REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/regs:vinit.ndx(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/rptr(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/wptr(4:0)#1.sva REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#3.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/MAC:MAC:or#3.itm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/MAC:mux#5.itm REGISTER_NAME MAC:mux#5.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm REGISTER_NAME MAC:mux#5.itm
directive set /fir/fir:core/core/MAC:MAC:nor#5.itm REGISTER_NAME MAC:MAC:nor#5.itm
directive set /fir/fir:core/core/nand.itm REGISTER_NAME MAC:MAC:nor#5.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#1.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm
directive set /fir/fir:core/core/MAC:mux#6.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-3:mul.itm
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC-3:mul.itm
