directive set /fir/fir:core/fir:core:conc/else:acc RESOURCE_NAME MAC:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc RESOURCE_NAME MAC:acc:rg
directive set /fir/fir:core/fir:core:conc/regs:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:else:acc RESOURCE_NAME MAC-3:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:else:acc RESOURCE_NAME MAC-3:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#6 RESOURCE_NAME MAC-8:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#5 RESOURCE_NAME MAC-8:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:acc#1 RESOURCE_NAME MAC-8:acc#1:rg
