directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/acc(32:3)#1.sva#1 REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC:i:asn#7.itm REGISTER_NAME MAC:i:asn#7.itm
directive set /fir/fir:core/core/MAC:i:asn#7.itm.1 REGISTER_NAME MAC:i:asn#7.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm.1 REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-3:mul.itm.1 REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC:acc#4.itm
directive set /fir/fir:core/core/MAC:acc#4.itm.1 REGISTER_NAME MAC:acc#4.itm
