directive set /fir/fir:core/core/MAC-10:acc#3.itm REGISTER_NAME MAC-10:acc#3.itm
directive set /fir/fir:core/core/MAC:asn.itm REGISTER_NAME MAC-10:acc#3.itm
directive set /fir/fir:core/core/MAC-15:mul.itm REGISTER_NAME MAC-15:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-15:mul.itm
directive set /fir/fir:core/core/MAC:acc#15.itm.1 REGISTER_NAME MAC-15:mul.itm
directive set /fir/fir:core/core/MAC-16:mul.itm REGISTER_NAME MAC-16:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-16:mul.itm
directive set /fir/fir:core/core/MAC:acc#6.itm.1 REGISTER_NAME MAC-16:mul.itm
directive set /fir/fir:core/core/MAC-12:mul.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC-14:mul.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#16.itm.1 REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-13:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC:acc#7.itm.1 REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC:acc#11.itm REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC:acc#9.itm.1 REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#8.itm.1 REGISTER_NAME MAC:acc#10.itm
