directive set /fir/fir:core/fir:core:conc/MAC:acc#17 RESOURCE_NAME MAC:acc#16:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#16 RESOURCE_NAME MAC:acc#16:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc RESOURCE_NAME MAC:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#6 RESOURCE_NAME MAC:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-14:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-4:mul:rg
