directive set /fir/fir:core/fir:core:conc/MAC:acc#19 RESOURCE_NAME MAC-15:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:acc#1 RESOURCE_NAME MAC-15:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#23 RESOURCE_NAME MAC:acc#22:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#22 RESOURCE_NAME MAC:acc#22:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:MAC:mux RESOURCE_NAME MAC-14:MAC:mux:rg
directive set /fir/fir:core/fir:core:conc/MAC-14:MAC:mux RESOURCE_NAME MAC-14:MAC:mux:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:MAC:mux RESOURCE_NAME MAC-12:MAC:mux:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:MAC:mux RESOURCE_NAME MAC-12:MAC:mux:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-15:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:mul RESOURCE_NAME MAC-15:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-17:mul RESOURCE_NAME MAC-16:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-16:mul RESOURCE_NAME MAC-16:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-14:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:acc#2 RESOURCE_NAME MAC-14:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-14:acc#2 RESOURCE_NAME MAC-14:acc#2:rg
