directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/acc(32:3)#6.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC-1:MAC:mux.itm REGISTER_NAME MAC-1:MAC:mux.itm
directive set /fir/fir:core/core/MAC-5:MAC:mux.itm REGISTER_NAME MAC-1:MAC:mux.itm
directive set /fir/fir:core/core/MAC-3:acc#2.psp.sva REGISTER_NAME MAC-3:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-6:acc#2.psp.sva REGISTER_NAME MAC-3:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC:acc#3.itm
directive set /fir/fir:core/core/MAC:i(1:0).sva REGISTER_NAME MAC:acc#3.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC:acc#6.itm
directive set /fir/fir:core/core/MAC:acc#9.itm REGISTER_NAME MAC:acc#6.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-6:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC-2:mul.itm
