directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/acc(32:3)#3.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC:mux#1.itm REGISTER_NAME MAC:mux#1.itm
directive set /fir/fir:core/core/MAC:mux#4.itm REGISTER_NAME MAC:mux#1.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-5:acc#2.itm REGISTER_NAME MAC-5:acc#2.itm
directive set /fir/fir:core/core/MAC:i(4:0).sva REGISTER_NAME MAC-5:acc#2.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-1:mul.itm
