directive set /fir/fir:core/core/regs:acc.itm REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/regs:vinit.ndx(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/rptr(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/wptr(4:0)#1.sva REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#3.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#4.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/MAC:mux.itm REGISTER_NAME MAC:mux.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#2.itm REGISTER_NAME MAC:mux.itm
directive set /fir/fir:core/core/MAC:mux#5.itm REGISTER_NAME MAC:mux#5.itm
directive set /fir/fir:core/core/MAC:mux#8.itm REGISTER_NAME MAC:mux#5.itm
directive set /fir/fir:core/core/MAC-4:acc#2.psp.sva REGISTER_NAME MAC-4:acc#2.psp.sva
directive set /fir/fir:core/core/MAC:i(4:0).sva REGISTER_NAME MAC-4:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-5:acc#2.itm REGISTER_NAME MAC-4:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:MAC:or#4.itm REGISTER_NAME MAC:MAC:or#4.itm
directive set /fir/fir:core/core/wptr(4:0)#4.sva#1 REGISTER_NAME MAC:MAC:or#4.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC:acc#4.itm
directive set /fir/fir:core/core/MAC:acc.itm REGISTER_NAME MAC:acc#4.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#1.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#1.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#1.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#1.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#1.itm
