directive set /fir/fir:core/fir:core:conc/regs:acc RESOURCE_NAME MAC-5:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:else:acc RESOURCE_NAME MAC-5:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:acc#1 RESOURCE_NAME MAC-2:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:acc#1 RESOURCE_NAME MAC-2:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#8 RESOURCE_NAME MAC:mux#6:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#6 RESOURCE_NAME MAC:mux#6:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
