directive set /fir/fir:core/core/regs:acc.itm REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/regs:vinit.ndx(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/rptr(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/wptr(4:0)#1.sva REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#6.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0).lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#3.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/acc(32:3).sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC:mux#19.itm REGISTER_NAME MAC:mux#19.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm REGISTER_NAME MAC:mux#19.itm
directive set /fir/fir:core/core/MAC:mux#17.itm REGISTER_NAME MAC:mux#17.itm
directive set /fir/fir:core/core/MAC:mux.itm REGISTER_NAME MAC:mux#17.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#2.itm REGISTER_NAME MAC:mux#17.itm
directive set /fir/fir:core/core/MAC-4:acc#2.psp.sva REGISTER_NAME MAC-4:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-8:acc#2.psp.sva REGISTER_NAME MAC-4:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-11:acc#2.itm REGISTER_NAME MAC-4:acc#2.psp.sva
directive set /fir/fir:core/core/MAC:i(4:0).sva(4:2) REGISTER_NAME MAC-4:acc#2.psp.sva
directive set /fir/fir:core/core/wptr(4:0)#4.sva#1 REGISTER_NAME wptr(4:0)#4.sva#1
directive set /fir/fir:core/core/wptr(4:0)#9.sva#1 REGISTER_NAME wptr(4:0)#4.sva#1
directive set /fir/fir:core/core/wptr(4:0)#5.lpi#2.dfm REGISTER_NAME wptr(4:0)#4.sva#1
directive set /fir/fir:core/core/wptr(4:0)#9.lpi#2.dfm REGISTER_NAME wptr(4:0)#4.sva#1
directive set /fir/fir:core/core/MAC:MAC:or#10.itm REGISTER_NAME wptr(4:0)#4.sva#1
directive set /fir/fir:core/core/MAC:MAC:nor#12.itm REGISTER_NAME MAC:MAC:nor#12.itm
directive set /fir/fir:core/core/MAC:MAC:nor#15.itm REGISTER_NAME MAC:MAC:nor#12.itm
directive set /fir/fir:core/core/MAC:MAC:nor#17.itm REGISTER_NAME MAC:MAC:nor#12.itm
directive set /fir/fir:core/core/MAC:MAC:nor#20.itm REGISTER_NAME MAC:MAC:nor#12.itm
directive set /fir/fir:core/core/MAC:mux#14.itm REGISTER_NAME MAC:mux#14.itm
directive set /fir/fir:core/core/MAC:mux#16.itm REGISTER_NAME MAC:mux#14.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-5:mul.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC-5:mul.itm
directive set /fir/fir:core/core/MAC:acc#7.itm REGISTER_NAME MAC-5:mul.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#2.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(31-16)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#3.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(31-16)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#4.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(31-16)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#1.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#1.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#4.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#1.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-7:mul.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC-7:mul.itm
directive set /fir/fir:core/core/MAC:acc#8.itm REGISTER_NAME MAC-7:mul.itm
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC-7:mul.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#5.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#5.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#1.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#5.itm
directive set /fir/fir:core/core/MAC-10:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-11:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC-10:mul.itm
