directive set /fir/fir:core/fir:core:conc/else:acc RESOURCE_NAME MAC-11:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:acc#2 RESOURCE_NAME MAC-11:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:acc#2 RESOURCE_NAME MAC-4:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:acc#2 RESOURCE_NAME MAC-4:acc#2:rg
directive set /fir/fir:core/fir:core:conc/regs:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:else:acc RESOURCE_NAME MAC-2:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:else:acc RESOURCE_NAME MAC-3:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:else:acc RESOURCE_NAME MAC-3:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:acc#1 RESOURCE_NAME MAC-11:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#9 RESOURCE_NAME MAC-11:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#18 RESOURCE_NAME MAC:mux#11:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#11 RESOURCE_NAME MAC:mux#11:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#15 RESOURCE_NAME MAC:mux#11:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-1:mul#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul#1 RESOURCE_NAME MAC-1:mul#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-11:mul:rg
