directive set /fir/fir:core/fir:core:conc/MAC-17:mul RESOURCE_NAME MAC-16:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-16:mul RESOURCE_NAME MAC-16:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-18:mul RESOURCE_NAME MAC-18:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-18:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-32:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-20:mul RESOURCE_NAME MAC-15:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:mul RESOURCE_NAME MAC-15:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-19:mul RESOURCE_NAME MAC-19:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-19:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-14:mul RESOURCE_NAME MAC-14:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-31:mul RESOURCE_NAME MAC-14:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-21:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-30:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-30:mul RESOURCE_NAME MAC-30:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-29:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-29:mul RESOURCE_NAME MAC-29:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-22:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-23:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-28:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-28:mul RESOURCE_NAME MAC-28:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-27:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-27:mul RESOURCE_NAME MAC-27:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-24:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-25:mul RESOURCE_NAME MAC-25:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-25:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-26:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-26:mul RESOURCE_NAME MAC-26:mul:rg
