directive set /fir/fir:core/fir:core:conc/MAC:acc#8 RESOURCE_NAME MAC:acc#10:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#10 RESOURCE_NAME MAC:acc#10:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-2:mul:rg
