directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/acc(32:3)#3.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC:acc#13.itm REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC:acc#10.psp.sva REGISTER_NAME MAC:acc#10.psp.sva
directive set /fir/fir:core/core/MAC:i(4:0).sva(1) REGISTER_NAME MAC:acc#10.psp.sva
directive set /fir/fir:core/core/MAC-10:MAC:mux.itm REGISTER_NAME MAC-10:MAC:mux.itm
directive set /fir/fir:core/core/MAC:mux#1.itm REGISTER_NAME MAC-10:MAC:mux.itm
directive set /fir/fir:core/core/MAC-15:MAC:mux.itm REGISTER_NAME MAC-15:MAC:mux.itm
directive set /fir/fir:core/core/MAC:mux.itm REGISTER_NAME MAC-15:MAC:mux.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-4:mul.itm
directive set /fir/fir:core/core/MAC:acc#23.itm REGISTER_NAME MAC-4:mul.itm
directive set /fir/fir:core/core/MAC-11:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-13:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-15:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#22.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-10:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-12:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-14:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-6:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC:acc#14.itm REGISTER_NAME MAC:acc#14.itm
directive set /fir/fir:core/core/MAC:acc#16.itm REGISTER_NAME MAC:acc#14.itm
