directive set /fir/fir:core/fir:core:conc/MAC-15:acc#1 RESOURCE_NAME MAC-15:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#17 RESOURCE_NAME MAC-15:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#20 RESOURCE_NAME MAC-2:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:acc#1 RESOURCE_NAME MAC-2:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:MAC:mux RESOURCE_NAME MAC-11:MAC:mux:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:MAC:mux RESOURCE_NAME MAC-11:MAC:mux:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-14:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-14:mul RESOURCE_NAME MAC-14:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:acc#2 RESOURCE_NAME MAC-13:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:acc#2 RESOURCE_NAME MAC-13:acc#2:rg
