directive set /fir/fir:core/core/MAC:asn#90.itm REGISTER_NAME MAC:asn#90.itm
directive set /fir/fir:core/core/asn.ncse.sva REGISTER_NAME MAC:asn#90.itm
directive set /fir/fir:core/core/MAC-28:mul.itm REGISTER_NAME MAC-28:mul.itm
directive set /fir/fir:core/core/MAC-30:mul.itm REGISTER_NAME MAC-28:mul.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC-28:mul.itm
directive set /fir/fir:core/core/MAC:acc.itm REGISTER_NAME MAC-28:mul.itm
directive set /fir/fir:core/core/MAC:acc#25.itm REGISTER_NAME MAC:acc#25.itm
directive set /fir/fir:core/core/MAC:acc#7.itm REGISTER_NAME MAC:acc#25.itm
directive set /fir/fir:core/core/MAC:acc#15.itm REGISTER_NAME MAC:acc#15.itm
directive set /fir/fir:core/core/MAC:acc#29.itm REGISTER_NAME MAC:acc#15.itm
directive set /fir/fir:core/core/MAC:acc#31.itm REGISTER_NAME MAC:acc#15.itm
directive set /fir/fir:core/core/MAC:acc#13.itm REGISTER_NAME MAC:acc#13.itm
directive set /fir/fir:core/core/MAC:acc#21.itm REGISTER_NAME MAC:acc#13.itm
directive set /fir/fir:core/core/MAC:acc#23.itm REGISTER_NAME MAC:acc#13.itm
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC:acc#13.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC:acc#13.itm
directive set /fir/fir:core/core/MAC:acc#9.itm REGISTER_NAME MAC:acc#13.itm
directive set /fir/fir:core/core/MAC-13:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-19:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-25:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC:acc#11.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC:acc#17.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC:acc#27.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#12.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#14.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#16.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#18.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#8.itm REGISTER_NAME MAC:acc#10.itm
