directive set /fir/fir:core/core/regs:acc.itm REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/regs:vinit.ndx(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/rptr(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/MAC:MAC:nor#32.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#35.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#37.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#40.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#42.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#45.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#47.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#50.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#52.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#55.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#57.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/MAC:MAC:nor#60.itm REGISTER_NAME MAC:MAC:nor#32.itm
directive set /fir/fir:core/core/wptr(4:0)#10.lpi#1.dfm REGISTER_NAME wptr(4:0)#10.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#15.lpi#1.dfm REGISTER_NAME wptr(4:0)#10.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#20.lpi#1.dfm REGISTER_NAME wptr(4:0)#10.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#30.lpi#1.dfm REGISTER_NAME wptr(4:0)#10.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#5.lpi#1.dfm REGISTER_NAME wptr(4:0)#10.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#2.lpi#1.dfm REGISTER_NAME wptr(4:0)#10.lpi#1.dfm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#1 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#10 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#4 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm
directive set /fir/fir:core/core/MAC:acc#25.itm REGISTER_NAME MAC:acc#25.itm
directive set /fir/fir:core/core/MAC:acc#29.itm REGISTER_NAME MAC:acc#25.itm
directive set /fir/fir:core/core/MAC:acc#3.itm REGISTER_NAME MAC:acc#25.itm
directive set /fir/fir:core/core/wptr(4:0)#12.lpi#1.dfm REGISTER_NAME wptr(4:0)#12.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#16.lpi#1.dfm REGISTER_NAME wptr(4:0)#12.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#18.lpi#1.dfm REGISTER_NAME wptr(4:0)#12.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#21.lpi#1.dfm REGISTER_NAME wptr(4:0)#12.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#23.lpi#1.dfm REGISTER_NAME wptr(4:0)#12.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#28.lpi#1.dfm REGISTER_NAME wptr(4:0)#12.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#4.lpi#1.dfm REGISTER_NAME wptr(4:0)#12.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#13.sva#1 REGISTER_NAME wptr(4:0)#13.sva#1
directive set /fir/fir:core/core/wptr(4:0)#18.sva#1 REGISTER_NAME wptr(4:0)#13.sva#1
directive set /fir/fir:core/core/wptr(4:0)#23.sva#1 REGISTER_NAME wptr(4:0)#13.sva#1
directive set /fir/fir:core/core/wptr(4:0)#28.sva#1 REGISTER_NAME wptr(4:0)#13.sva#1
directive set /fir/fir:core/core/wptr(4:0)#3.sva#1 REGISTER_NAME wptr(4:0)#13.sva#1
directive set /fir/fir:core/core/wptr(4:0)#8.sva#1 REGISTER_NAME wptr(4:0)#13.sva#1
directive set /fir/fir:core/core/wptr(4:0)#13.lpi#1.dfm REGISTER_NAME wptr(4:0)#13.sva#1
directive set /fir/fir:core/core/wptr(4:0)#29.lpi#1.dfm REGISTER_NAME wptr(4:0)#13.sva#1
directive set /fir/fir:core/core/wptr(4:0)#14.lpi#1.dfm REGISTER_NAME wptr(4:0)#14.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#22.lpi#1.dfm REGISTER_NAME wptr(4:0)#14.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#7.lpi#1.dfm REGISTER_NAME wptr(4:0)#14.lpi#1.dfm
directive set /fir/fir:core/core/MAC:MAC:or#30.itm REGISTER_NAME wptr(4:0)#14.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#17.lpi#1.dfm REGISTER_NAME wptr(4:0)#17.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#24.lpi#1.dfm REGISTER_NAME wptr(4:0)#17.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#9.lpi#1.dfm REGISTER_NAME wptr(4:0)#17.lpi#1.dfm
directive set /fir/fir:core/core/MAC:acc#15.itm REGISTER_NAME MAC:acc#15.itm
directive set /fir/fir:core/core/MAC:acc#23.itm REGISTER_NAME MAC:acc#15.itm
directive set /fir/fir:core/core/MAC:acc#27.itm REGISTER_NAME MAC:acc#15.itm
directive set /fir/fir:core/core/MAC:acc#7.itm REGISTER_NAME MAC:acc#15.itm
directive set /fir/fir:core/core/wptr(4:0)#19.lpi#1.dfm REGISTER_NAME wptr(4:0)#19.lpi#1.dfm
directive set /fir/fir:core/core/wptr(4:0)#26.lpi#1.dfm REGISTER_NAME wptr(4:0)#19.lpi#1.dfm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-9:mul.itm
directive set /fir/fir:core/core/MAC:acc#11.itm REGISTER_NAME MAC-9:mul.itm
directive set /fir/fir:core/core/MAC:acc#19.itm REGISTER_NAME MAC-9:mul.itm
directive set /fir/fir:core/core/MAC:acc#21.itm REGISTER_NAME MAC-9:mul.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC-9:mul.itm
directive set /fir/fir:core/core/MAC:acc#9.itm REGISTER_NAME MAC-9:mul.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#5 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#5
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm#14 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#5
directive set /fir/fir:core/core/MAC-12:mul.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC-6:mul.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#12.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#14.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#16.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#18.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc#8.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:acc.itm REGISTER_NAME MAC-12:mul.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#7 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#7
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm#4 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#7
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#9 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#9
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm#5 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#9
directive set /fir/fir:core/core/MAC-13:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-15:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-17:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-19:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-21:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-23:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-25:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-27:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-29:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-31:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC:acc#13.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC:acc#17.itm REGISTER_NAME MAC-13:mul.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#11 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#11
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#2 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#11
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm#1 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#11
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#13 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#13
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm#3 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#13
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm#7 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#13
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#12 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#12
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm#3 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#12
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm#2 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#12
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16).itm#6 REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0).itm#12
