directive set /fir/fir:core/fir:core:conc/MAC-32:acc#1 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#17 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#31 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#33 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#29 RESOURCE_NAME MAC:acc#27:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#27 RESOURCE_NAME MAC:acc#27:rg
directive set /fir/fir:core/fir:core:conc/regs:acc RESOURCE_NAME MAC-1:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:else:acc RESOURCE_NAME MAC-1:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:else:acc RESOURCE_NAME MAC-13:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:else:acc RESOURCE_NAME MAC-13:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-28:else:acc RESOURCE_NAME MAC-13:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:else:acc RESOURCE_NAME MAC-26:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-26:else:acc RESOURCE_NAME MAC-26:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-21:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-23:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-19:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-27:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-31:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-17:mul RESOURCE_NAME MAC-17:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-30:mul RESOURCE_NAME MAC-17:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-25:mul RESOURCE_NAME MAC-25:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-26:mul RESOURCE_NAME MAC-25:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-29:mul RESOURCE_NAME MAC-29:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-29:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-22:mul RESOURCE_NAME MAC-18:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-18:mul RESOURCE_NAME MAC-18:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-14:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-14:mul RESOURCE_NAME MAC-14:mul:rg
