directive set /fir/fir:core/core/regs:acc.itm REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/regs:vinit.ndx(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/rptr(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/wptr(4:0)#1.sva REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#11.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#6.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#7.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/MAC:MAC:or#12.itm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/MAC:mux#14.itm REGISTER_NAME MAC:mux#14.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#4.itm REGISTER_NAME MAC:mux#14.itm
directive set /fir/fir:core/core/MAC:mux#15.itm REGISTER_NAME MAC:mux#15.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#3.itm REGISTER_NAME MAC:mux#15.itm
directive set /fir/fir:core/core/MAC:mux#13.itm REGISTER_NAME MAC:mux#13.itm
directive set /fir/fir:core/core/MAC:mux#16.itm REGISTER_NAME MAC:mux#13.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#6.itm REGISTER_NAME MAC:mux#13.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#1.itm REGISTER_NAME MAC:mux#13.itm
directive set /fir/fir:core/core/MAC:MAC:nor#14.itm REGISTER_NAME MAC:MAC:nor#14.itm
directive set /fir/fir:core/core/MAC:MAC:nor#17.itm REGISTER_NAME MAC:MAC:nor#14.itm
directive set /fir/fir:core/core/MAC:MAC:nor#19.itm REGISTER_NAME MAC:MAC:nor#14.itm
directive set /fir/fir:core/core/MAC:MAC:nor#22.itm REGISTER_NAME MAC:MAC:nor#14.itm
directive set /fir/fir:core/core/MAC:MAC:nor#24.itm REGISTER_NAME MAC:MAC:nor#14.itm
directive set /fir/fir:core/core/nand.itm REGISTER_NAME MAC:MAC:nor#14.itm
directive set /fir/fir:core/core/MAC:mux#17.itm REGISTER_NAME MAC:mux#17.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#5.itm REGISTER_NAME MAC:mux#17.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#11.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#13.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#7.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-10:acc#2.psp.sva REGISTER_NAME MAC-10:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-11:acc#2.psp.sva REGISTER_NAME MAC-10:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-4:acc#2.psp.sva REGISTER_NAME MAC-10:acc#2.psp.sva
directive set /fir/fir:core/core/MAC:acc.psp.sva REGISTER_NAME MAC:acc.psp.sva
directive set /fir/fir:core/core/MAC:acc#4.psp.sva REGISTER_NAME MAC:acc.psp.sva
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#1.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#1.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#3.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#1.itm
directive set /fir/fir:core/core/MAC:mux#21.itm REGISTER_NAME MAC:mux#21.itm
directive set /fir/fir:core/core/MAC:mux.itm REGISTER_NAME MAC:mux#21.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC:acc#5.itm
directive set /fir/fir:core/core/MAC:i(1:0).sva REGISTER_NAME MAC:acc#5.itm
directive set /fir/fir:core/core/MAC:acc#3.psp.sva REGISTER_NAME MAC:acc#5.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#2.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#5.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#2.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/wptr(4:0)#12.lpi#2.dfm REGISTER_NAME wptr(4:0)#12.lpi#2.dfm
directive set /fir/fir:core/core/wptr(4:0)#3.lpi#2.dfm REGISTER_NAME wptr(4:0)#12.lpi#2.dfm
directive set /fir/fir:core/core/wptr(4:0)#8.lpi#2.dfm REGISTER_NAME wptr(4:0)#12.lpi#2.dfm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#4.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#4.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#4.itm
directive set /fir/fir:core/core/wptr(4:0)#1.sva#2 REGISTER_NAME wptr(4:0)#1.sva#2
directive set /fir/fir:core/core/wptr(4:0)#4.sva#1 REGISTER_NAME wptr(4:0)#1.sva#2
directive set /fir/fir:core/core/wptr(4:0)#9.sva#1 REGISTER_NAME wptr(4:0)#1.sva#2
directive set /fir/fir:core/core/wptr(4:0)#9.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva#2
directive set /fir/fir:core/core/MAC:acc#14.itm REGISTER_NAME MAC:acc#14.itm
directive set /fir/fir:core/core/MAC:acc#16.itm REGISTER_NAME MAC:acc#14.itm
directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME MAC:acc#14.itm
directive set /fir/fir:core/core/MAC-10:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-12:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-8:mul.itm
directive set /fir/fir:core/core/MAC:acc#12.itm REGISTER_NAME MAC-8:mul.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC-8:mul.itm
directive set /fir/fir:core/core/MAC:acc#8.itm REGISTER_NAME MAC-8:mul.itm
