directive set /fir/fir:core/fir:core:conc/regs:acc RESOURCE_NAME MAC-12:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:else:acc RESOURCE_NAME MAC-12:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:else:acc RESOURCE_NAME MAC-12:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:else:acc RESOURCE_NAME MAC-13:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:else:acc RESOURCE_NAME MAC-13:else:acc:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#16 RESOURCE_NAME MAC-13:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:acc#1 RESOURCE_NAME MAC-13:acc#1:rg
directive set /fir/fir:core/fir:core:conc/else:acc RESOURCE_NAME MAC-11:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:acc#2 RESOURCE_NAME MAC-11:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#20 RESOURCE_NAME MAC:mux#20:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#33 RESOURCE_NAME MAC:mux#20:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#18 RESOURCE_NAME MAC:mux#18:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#31 RESOURCE_NAME MAC:mux#18:rg
