directive set /fir/fir:core/fir:core:conc/MAC-32:acc#1 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#20 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#24 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#28 RESOURCE_NAME MAC:acc#26:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#26 RESOURCE_NAME MAC:acc#26:rg
directive set /fir/fir:core/fir:core:conc/MAC-30:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-19:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-25:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-28:mul RESOURCE_NAME MAC-22:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-22:mul RESOURCE_NAME MAC-22:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-27:mul RESOURCE_NAME MAC-27:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-27:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-26:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-18:mul RESOURCE_NAME MAC-18:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-18:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-17:mul RESOURCE_NAME MAC-17:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-17:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-29:mul RESOURCE_NAME MAC-21:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-21:mul RESOURCE_NAME MAC-21:mul:rg
