directive set /fir/fir:core/fir:core:conc/MAC-19:mul RESOURCE_NAME MAC-19:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-21:mul RESOURCE_NAME MAC-19:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-20:mul RESOURCE_NAME MAC-15:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:mul RESOURCE_NAME MAC-15:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-17:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-17:mul RESOURCE_NAME MAC-17:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-16:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-16:mul RESOURCE_NAME MAC-16:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-5:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-5:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-14:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-32:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-18:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#20 RESOURCE_NAME MAC:acc#20:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#27 RESOURCE_NAME MAC:acc#20:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#26 RESOURCE_NAME MAC:acc#22:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#22 RESOURCE_NAME MAC:acc#22:rg
directive set /fir/fir:core/fir:core:conc/MAC-32:acc#1 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#31 RESOURCE_NAME MAC-32:acc#1:rg
