directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-3:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-3:mul.itm
directive set /fir/fir:core/core/MAC-10:acc#2.psp.sva REGISTER_NAME MAC-10:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-1:acc#2.psp.sva REGISTER_NAME MAC-10:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-11:MAC:mux.itm REGISTER_NAME MAC-11:MAC:mux.itm
directive set /fir/fir:core/core/MAC:mux#1.itm REGISTER_NAME MAC-11:MAC:mux.itm
directive set /fir/fir:core/core/MAC-12:MAC:mux.itm REGISTER_NAME MAC-12:MAC:mux.itm
directive set /fir/fir:core/core/MAC:mux#2.itm REGISTER_NAME MAC-12:MAC:mux.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC:acc#5.itm
directive set /fir/fir:core/core/MAC:i(1:0).sva REGISTER_NAME MAC:acc#5.itm
directive set /fir/fir:core/core/MAC:acc#14.itm REGISTER_NAME MAC:acc#14.itm
directive set /fir/fir:core/core/MAC:acc#8.itm REGISTER_NAME MAC:acc#14.itm
directive set /fir/fir:core/core/MAC-11:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-13:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-6:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#11.itm REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC:acc#15.itm REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC:acc#9.itm REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/acc(32:3)#7.sva REGISTER_NAME MAC:acc#11.itm
directive set /fir/fir:core/core/MAC-10:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-12:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-10:mul.itm
