directive set /fir/fir:core/fir:core:conc/MAC:mux#3 RESOURCE_NAME MAC:mux#3:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#9 RESOURCE_NAME MAC:mux#3:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:acc#2 RESOURCE_NAME MAC-10:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:acc#2 RESOURCE_NAME MAC-10:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:acc#2 RESOURCE_NAME MAC-1:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:acc#2 RESOURCE_NAME MAC-1:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#9 RESOURCE_NAME MAC:acc#15:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#15 RESOURCE_NAME MAC:acc#15:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#14 RESOURCE_NAME MAC:acc#14:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#8 RESOURCE_NAME MAC:acc#14:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:MAC:mux RESOURCE_NAME MAC-11:MAC:mux:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:MAC:mux RESOURCE_NAME MAC-11:MAC:mux:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-2:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-5:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-5:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-13:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-13:mul:rg
