directive set /fir/fir:core/fir:core:conc/MAC-32:acc#1 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#20 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC:acc#29 RESOURCE_NAME MAC-32:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-32:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-22:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-22:mul RESOURCE_NAME MAC-22:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-27:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-27:mul RESOURCE_NAME MAC-27:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-29:mul RESOURCE_NAME MAC-27:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-31:mul RESOURCE_NAME MAC-27:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-13:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-15:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-17:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-19:mul RESOURCE_NAME MAC-19:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-21:mul RESOURCE_NAME MAC-19:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-23:mul RESOURCE_NAME MAC-19:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-25:mul RESOURCE_NAME MAC-19:mul:rg
