directive set /fir/fir:core/core/MAC-10:acc#3.itm REGISTER_NAME MAC-10:acc#3.itm
directive set /fir/fir:core/core/MAC:asn.itm REGISTER_NAME MAC-10:acc#3.itm
directive set /fir/fir:core/core/MAC-15:mul.itm REGISTER_NAME MAC-15:mul.itm
directive set /fir/fir:core/core/MAC:acc#11.itm REGISTER_NAME MAC-15:mul.itm
directive set /fir/fir:core/core/MAC:acc#15.itm REGISTER_NAME MAC-15:mul.itm
directive set /fir/fir:core/core/MAC:acc#17.itm REGISTER_NAME MAC-15:mul.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC-15:mul.itm
directive set /fir/fir:core/core/MAC-16:mul.itm REGISTER_NAME MAC-16:mul.itm
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC-16:mul.itm
directive set /fir/fir:core/core/MAC:acc#12.itm REGISTER_NAME MAC-16:mul.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC-16:mul.itm
directive set /fir/fir:core/core/MAC:acc#8.itm REGISTER_NAME MAC-16:mul.itm
directive set /fir/fir:core/core/MAC:acc#7.itm REGISTER_NAME MAC:acc#7.itm
directive set /fir/fir:core/core/MAC:acc#9.itm REGISTER_NAME MAC:acc#7.itm
