directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/acc(32:3)#9.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#13.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC-10:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-12:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-6:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-11:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#11.itm REGISTER_NAME MAC-11:mul.itm
