directive set /fir/fir:core/fir:core:conc/MAC:acc#10 RESOURCE_NAME MAC-8:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:acc#1 RESOURCE_NAME MAC-8:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-8:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-8:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-12:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-12:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-3:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-3:mul:rg
