directive set /fir/fir:core/core/regs:acc.itm REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/regs:vinit.ndx(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/rptr(4:0).sva REGISTER_NAME regs:acc.itm
directive set /fir/fir:core/core/wptr(4:0)#1.sva REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#11.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#6.lpi#2.dfm REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#4.sva#1 REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/wptr(4:0)#9.sva#1 REGISTER_NAME wptr(4:0)#1.sva
directive set /fir/fir:core/core/acc(32:3)#1.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/acc(32:3)#9.sva REGISTER_NAME acc(32:3)#1.sva
directive set /fir/fir:core/core/MAC:mux#18.itm REGISTER_NAME MAC:mux#18.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#5.itm REGISTER_NAME MAC:mux#18.itm
directive set /fir/fir:core/core/MAC:mux#16.itm REGISTER_NAME MAC:mux#16.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#4.itm REGISTER_NAME MAC:mux#16.itm
directive set /fir/fir:core/core/MAC:mux#17.itm REGISTER_NAME MAC:mux#17.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#2.itm REGISTER_NAME MAC:mux#17.itm
directive set /fir/fir:core/core/MAC:MAC:nor#13.itm REGISTER_NAME MAC:MAC:nor#13.itm
directive set /fir/fir:core/core/MAC:MAC:nor#16.itm REGISTER_NAME MAC:MAC:nor#13.itm
directive set /fir/fir:core/core/MAC:MAC:nor#18.itm REGISTER_NAME MAC:MAC:nor#13.itm
directive set /fir/fir:core/core/MAC:MAC:nor#21.itm REGISTER_NAME MAC:MAC:nor#13.itm
directive set /fir/fir:core/core/nand.itm REGISTER_NAME MAC:MAC:nor#13.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC:acc#4.itm
directive set /fir/fir:core/core/MAC:i(4:2).sva REGISTER_NAME MAC:acc#4.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:acc#13.itm REGISTER_NAME MAC-2:mul.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#2.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#4.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0).itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#1.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/MAC:mux#14.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#2.itm
directive set /fir/fir:core/core/wptr(4:0)#8.lpi#2.dfm REGISTER_NAME wptr(4:0)#8.lpi#2.dfm
directive set /fir/fir:core/core/wptr(4:0)#9.lpi#2.dfm REGISTER_NAME wptr(4:0)#8.lpi#2.dfm
directive set /fir/fir:core/core/MAC:MAC:or#11.itm REGISTER_NAME wptr(4:0)#8.lpi#2.dfm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#3.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#3.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(15-0)#5.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#3.itm
directive set /fir/fir:core/core/MAC:slc(regs:rsci.qa_d)(31-16)#3.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#3.itm
directive set /fir/fir:core/core/MAC:mux#13.itm REGISTER_NAME MAC:slc(regs:rsci.qa_d)(15-0)#3.itm
directive set /fir/fir:core/core/wptr(4:0)#10.lpi#2.dfm REGISTER_NAME wptr(4:0)#10.lpi#2.dfm
directive set /fir/fir:core/core/wptr(4:0)#3.lpi#2.dfm REGISTER_NAME wptr(4:0)#10.lpi#2.dfm
directive set /fir/fir:core/core/wptr(4:0)#7.lpi#2.dfm REGISTER_NAME wptr(4:0)#10.lpi#2.dfm
directive set /fir/fir:core/core/wptr(4:0).lpi#2.dfm REGISTER_NAME wptr(4:0)#10.lpi#2.dfm
directive set /fir/fir:core/core/MAC-11:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#12.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#5.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#14.itm REGISTER_NAME MAC:acc#14.itm
directive set /fir/fir:core/core/MAC:acc#7.itm REGISTER_NAME MAC:acc#14.itm
