directive set /fir/fir:core/core/MAC:asn#62.itm REGISTER_NAME MAC:asn#62.itm
directive set /fir/fir:core/core/regs(1).sva REGISTER_NAME MAC:asn#62.itm
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#12.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#14.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#16.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#18.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#20.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#26.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc.itm.1 REGISTER_NAME MAC:acc#10.itm
directive set /fir/fir:core/core/MAC:acc#22.itm REGISTER_NAME MAC:acc#22.itm
directive set /fir/fir:core/core/MAC:acc#24.itm REGISTER_NAME MAC:acc#22.itm
directive set /fir/fir:core/core/MAC:acc#30.itm REGISTER_NAME MAC:acc#22.itm
directive set /fir/fir:core/core/MAC:acc#4.itm REGISTER_NAME MAC:acc#22.itm
directive set /fir/fir:core/core/MAC-11:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-13:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-15:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-17:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-19:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-21:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-23:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-25:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-27:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-29:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-31:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#29.itm.1 REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC:acc#27.itm REGISTER_NAME MAC-11:mul.itm
directive set /fir/fir:core/core/MAC-10:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-12:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-14:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-16:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-18:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-20:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-22:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-24:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-26:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-28:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-30:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-32:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-6:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC:acc#28.itm.1 REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC:acc#28.itm REGISTER_NAME MAC:acc#28.itm
directive set /fir/fir:core/core/MAC:acc#8.itm REGISTER_NAME MAC:acc#28.itm
