directive set /fir/fir:core/core/MAC:mux#1.itm REGISTER_NAME MAC:mux#1.itm
directive set /fir/fir:core/core/MAC:mux#8.itm REGISTER_NAME MAC:mux#1.itm
directive set /fir/fir:core/core/MAC-3:mul.itm REGISTER_NAME MAC-3:mul.itm
directive set /fir/fir:core/core/MAC-7:mul.itm REGISTER_NAME MAC-3:mul.itm
directive set /fir/fir:core/core/MAC-9:acc#2.psp.sva REGISTER_NAME MAC-9:acc#2.psp.sva
directive set /fir/fir:core/core/MAC:i(4:0).sva(4:2) REGISTER_NAME MAC-9:acc#2.psp.sva
directive set /fir/fir:core/core/MAC-11:acc#2.itm REGISTER_NAME MAC-11:acc#2.itm
directive set /fir/fir:core/core/MAC-1:acc#2.psp.sva REGISTER_NAME MAC-11:acc#2.itm
directive set /fir/fir:core/core/MAC:mux#10.itm REGISTER_NAME MAC:mux#10.itm
directive set /fir/fir:core/core/MAC:mux#7.itm REGISTER_NAME MAC:mux#10.itm
directive set /fir/fir:core/core/MAC-1:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-9:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-5:mul.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC:acc#6.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC:acc.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC:acc#10.itm REGISTER_NAME MAC-1:mul.itm
directive set /fir/fir:core/core/MAC-10:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-11:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-2:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-4:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-6:mul.itm REGISTER_NAME MAC-10:mul.itm
directive set /fir/fir:core/core/MAC-8:mul.itm REGISTER_NAME MAC-10:mul.itm
