directive set /fir/fir:core/fir:core:conc/MAC:acc#6 RESOURCE_NAME MAC-10:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:acc#1 RESOURCE_NAME MAC-10:acc#1:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:acc#2 RESOURCE_NAME MAC-4:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:acc#2 RESOURCE_NAME MAC-4:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:acc#2 RESOURCE_NAME MAC-2:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-6:acc#2 RESOURCE_NAME MAC-2:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:acc#2 RESOURCE_NAME MAC-1:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:acc#2 RESOURCE_NAME MAC-1:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:acc#2 RESOURCE_NAME MAC-1:acc#2:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#9 RESOURCE_NAME MAC:mux#3:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#3 RESOURCE_NAME MAC:mux#3:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#4 RESOURCE_NAME MAC:mux#3:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#6 RESOURCE_NAME MAC:mux#2:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#2 RESOURCE_NAME MAC:mux#2:rg
directive set /fir/fir:core/fir:core:conc/MAC:mux#5 RESOURCE_NAME MAC:mux#2:rg
directive set /fir/fir:core/fir:core:conc/MAC-7:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-4:mul RESOURCE_NAME MAC-4:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-2:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-11:mul RESOURCE_NAME MAC-11:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-10:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-9:mul RESOURCE_NAME MAC-10:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-8:mul RESOURCE_NAME MAC-5:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-5:mul RESOURCE_NAME MAC-5:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /fir/fir:core/fir:core:conc/MAC-3:mul RESOURCE_NAME MAC-1:mul:rg
